# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Stellantis.CitroenUpdate
PackageVersion: 1.5.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 34f18d20-cd77-5abe-b8da-25524d95050a
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/citroen/Citroen_Update_Setup_0.1.24.exe
  InstallerSha256: 1F6B96468350E2B0831B3455DDE438DB08C862DC9104F711C23EA1F499D52E7B
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/citroen/Citroen_Update_Setup_0.1.24.exe
  InstallerSha256: 1F6B96468350E2B0831B3455DDE438DB08C862DC9104F711C23EA1F499D52E7B
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
