# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Stellantis.CitroenUpdate
PackageVersion: 1.5.2
PackageLocale: en
Publisher: PSA Automobiles SA
PublisherUrl: https://www.stellantis.com/en
PrivacyUrl: https://www.stellantis.com/en/privacy
Author: Stellantis N.V.
PackageName: Citroen Update
PackageUrl: https://www.citroen.co.uk/buy/map-update.html
License: Proprietary
Copyright: Copyright © 2023 Stellantis N.V.
ShortDescription: |-
  The application «CITROËN UPDATE» allows to updating the navigation system and the mapping.
  This application prepares the USB stick that you will need to use in your vehicle.
Moniker: citroen-update
Tags:
- stellantis
- psa
- citroen
- nav
- satnav
- car
- update
ManifestType: defaultLocale
ManifestVersion: 1.5.0
