# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Stellantis.OpelUpdate
PackageVersion: 1.5.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: e7416028-04bb-5421-a775-0ed8d70f442e
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/opel/opel_update.exe
  InstallerSha256: C0A05D047F70F98408A90E95D9799C4AACD5FA62C3A86A255DE691E50E919D90
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/opel/opel_update.exe
  InstallerSha256: C0A05D047F70F98408A90E95D9799C4AACD5FA62C3A86A255DE691E50E919D90
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
