# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Stellantis.PeugeotUpdate
PackageVersion: 1.5.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 46cf01d6-a405-5b47-a44f-4dd61ad5f7c2
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/peugeot/peugeot_update.exe
  InstallerSha256: 86ECFE85F923543D1DE78AE7565C8B911E5C9BF72425ABF5436F63895614C872
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/peugeot/peugeot_update.exe
  InstallerSha256: 86ECFE85F923543D1DE78AE7565C8B911E5C9BF72425ABF5436F63895614C872
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
