# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Stellantis.VauxhallUpdate
PackageVersion: 1.5.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 4218322f-00bf-51c8-8a2d-a9b3b5503f39
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/vauxhall/vauxhall_update.exe
  InstallerSha256: 45D366092228D06246D695238578853AC473042114F69DE2472EC0C66FB5B390
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/vauxhall/vauxhall_update.exe
  InstallerSha256: 45D366092228D06246D695238578853AC473042114F69DE2472EC0C66FB5B390
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
