# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Stellantis.DSUpdate
PackageVersion: 1.5.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: e6d06ca5-4b5d-555a-82f9-96eee53026c3
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/ds/installer.exe
  InstallerSha256: 21D4380D5FCCC2DF284BDA0A29F4FC066C6FEDBA00B3FE75548B069D6220E2DF
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://d1tik0o5ahgjm.cloudfront.net/ds/installer.exe
  InstallerSha256: 21D4380D5FCCC2DF284BDA0A29F4FC066C6FEDBA00B3FE75548B069D6220E2DF
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
